# Site settings
title: ROS Index
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  A community-maintained index of known ROS packages.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://rosindex.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  rosindex
destination: _deploy

# Build settings
markdown: redcarpet
kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

redcarpet:
  extensions:
    - fenced_code_blocks
    - autolink
    - no_intra_emphasis

highlighter: pygments

checkout_threads: 5
checkout_path: _checkout

exclude:
  - _checkout
  - node_modules
  - Rakefile
  - README.md

rosdistro_path: _rosdistro
repos_path: _repos

# ROS distros to look for
distros:
  - 'indigo'
  - 'hydro'
  - 'groovy'
old_distros:
  - 'fuerte'
  - 'electric'
  - 'diamondback'
  - 'c-turtle'

# package list page
packages_per_page: 50
repos_per_page: 50

# uncomment the following line for testing (limit the number of indexed repos)
max_repos: 00
