# package list page
packages_per_page: 3
repos_per_page: 3

# set the following to a non-zero value for testing (limit the number of indexed repos)
max_repos: 10

destination: _devel

checkout_threads: 1
