# Site settings
title: ROS Index
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  a community-maintained index of robotics software
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://rosindex.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  rosindex
destination: _deploy

# Build settings
markdown: redcarpet
kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

redcarpet:
  extensions:
    - fenced_code_blocks
    - autolink
    - no_intra_emphasis

highlighter: pygments

checkout_threads: 3
checkout_path: _checkout

# domains which are broken
domain_blacklist:
  - 'kforge.ros.org'
  - 'code.in.tum.de'

use_cached: true
cache_filename: _deploy_cache.db

exclude:
  - _deploy_cache.db
  - _devel_cace.db
  - _ruby_libs
  - _checkout
  - node_modules
  - Rakefile
  - README.md

rosdistro_path: _rosdistro
repos_path: _repos
index_old_doc_paths: false

# ROS distros to look for
distros:
  - 'jade'
  - 'indigo'
  - 'hydro'
old_distros:
  - 'groovy'
  - 'fuerte'
  - 'electric'
  - 'diamondback'

# package list page
packages_per_page: 50
repos_per_page: 50

# uncomment the following line for testing (limit the number of indexed repos)
max_repos: 00
