# Site settings
title: ROS Index
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  a community-maintained index of robotics software
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://rosindex.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  rosindex
destination: _deploy

# Build settings
markdown: redcarpet
kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

redcarpet:
  extensions:
    - fenced_code_blocks
    - autolink
    - no_intra_emphasis
    - with_toc_data
    - html_toc
    - tables

highlighter: pygments

# If true, this begins with an existing db
use_db_cache: true
db_cache_filename: _caches/_deploy_cache.db

# If true, this skips finding repos based on the repo sources
skip_discover: true
# If true, this skips updating the known repos
skip_update: true
# If true, this skips scraping the cloned repos
skip_scrape: true
# If true, this skips generating the search index
skip_search_index: false

checkout_threads: 1
checkout_path: _checkout

# if non-empty, only scrape these packages (useful for debugging / partial db updates)
repo_id_whitelist: []

# domains which are broken
domain_blacklist:
  - 'kforge.ros.org'
  - 'code.in.tum.de'

exclude:
  - _scripts
  - _caches
  - _rosdistro
  - _rosforks
  - _deploy_cache.db
  - _devel_cace.db
  - _ruby_libs
  - _checkout
  - node_modules
  - Rakefile
  - README.md

rosdistro_path: _rosdistro
repos_path: _rosforks/repos
index_old_doc_paths: false

# ROS distros to look for
distros:
  - 'jade'
  - 'indigo'
  - 'hydro'
old_distros:
  - 'groovy'
  - 'fuerte'
  - 'electric'
  - 'diamondback'

# package list page
packages_per_page: 50
repos_per_page: 50

# uncomment the following line for testing (limit the number of indexed repos)
max_repos: 00
