# package list page
packages_per_page: 3
repos_per_page: 3

# set the following to a non-zero value for testing (limit the number of indexed repos)
max_repos: 2

# If true, this begins with an existing db
use_db_cache: true
# If true, this skips finding repos based on the repo sources
skip_discover: true
# If true, this skips updating the known repos
skip_update: true
# If true, this skips scraping the cloned repos
skip_scrape: true
# If true, this skips generating the search index
skip_search_index: true

checkout_threads: 1

# if non-empty, only scrape these packages (useful for debugging / partial db updates)
scrape_whitelist: []
